### ISSUE TITLE
small inconsistencies

### ISSUE THREAD

**Issue by mattjohndavidson** [dacb/codebase_conda#2]
part of SWEDS class, and there were a few inconsistencies I ran into. None were difficult to correct, but wanted to flag.
1) .travis.yml refers to branch "master", and I think the new default is "main"
2) .travis.yml uses a conda environment called "test-environment", while the readme directions have you create an environment called "test_env"

**Comment by dacb** [comment]
Thank you, @mattjohndavidson!  I have addressed these comments with commits 5390c51  and b3af308 .  Please reopen if you this is not resolved.
